# Comment that will be sent if an issue is judged to be closed.
comment: "This issue is closed because you have not filled in our article checklist. Please read it."
issueConfigs:
# There can be several configs for different kind of issues.
- content:
# Example 1: article submission
  #### Grammar & plagiarism checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) - [Grammarly](https://grammarly.com) 
- [x] Please place your article through a 3rd party plagiarism checker. We suggest using Quetext, [this tool](https://www.quetext.com/) is free and has a daily limit. **We typically accept articles with 10% or less.**
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?
- content:
# Example 2: feature request
  - "Motivation / Use Case"
  - "Expected Behavior"
  - "Other Information"
# Optional configuration:
#
# whether the keywords are case-insensitive
# default value is false, which means keywords are case-sensitive
caseInsensitive: false
# the label that will be added when the bot close an issue
# The bot will only add a label if this property is set.
label: "closed by bot"
# The bot will ignore any issues that are opened or reopened by the user names in exception
exception:
  - "hectorkambow"
# The issue is judged to be legal if it includes all keywords from any of these two configs.
# Or it will be closed by the app.
