# Generated by Django 3.2.6 on 2021-08-18 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='Facility',
        ),
    ]
