# Generated by Django 3.2.6 on 2021-08-20 05:36

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path


DATA_FILENAME = 'export.json'
def load_data(apps, schema_editor):
    Facility = apps.get_model('facilities', 'Facility')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile), encoding="utf8") as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                objType = obj['type']
                if objType == 'node':
                    tags = obj['tags']
                    name = tags.get('name','no-name')
                    longitude = obj.get('lon', 0)
                    latitude = obj.get('lat', 0)
                    location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                    Facility(name=name, location=location).save()
            except KeyError:
                pass

class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_rename_shop_facility'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
