name: Auto Comment
on: [issues, pull_request]
permissions:
  pull-requests: write
  jobs:
    run:
      runs-on: ubuntu-latest
      steps:
        - uses: wow-actions/auto-comment@v1
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            issuesOpened: |
              👋 @{{ author }}
              Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
              Please make sure you have given us as much context as possible.

            pullRequestOpened: |
              👋 @{{ author }}
              "Good afternoon and thank you for submitting your pull request for review and publishing.
              
              Your pull request has entered our queue and will be reviewed by our team of peer reviewers as soon as possible. 🚀
              
              All articles are reviewed in the order in which they were received.
              
              Thank you.   