name: Auto Comment
on: [issues, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpenedReactions: 'hooray, +1'
          issuesOpenedComment: |
            👋 @{{ author }}
            Good afternoon and thank you for submitting your topic suggestion.
            Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

          pullRequestOpened: |
            👋 @{{ author }},

            Thanks for submitting this PR.

            Your PR has entered our reviewing queue. Please wait until a peer-reviewer pings you to get started with the review.

            Meanwhile, we suggest you to go through approved PRs/published articles to see if you have missed out anything. This would help us avoid any potential closure of the PR.

            Thanks.